### ISSUE TITLE
Entitlements string back to ADAL in v0.2.0

### ISSUE THREAD

**Issue by jthake-msft** [Azure-Samples/ms-identity-mobile-apple-swift-objc#34]
I just spent an hour trying to work out why my code was continually looping on the sign in screen.

I had changed my podfile to point to 0.2.0, and grabbed the changes in the sample code from what used to work with 0.1.0 to 0.2.0. I had changed my viewcontroller AND the appdelegate.swift.

I was getting this error in the acquireTokenInteractively()
> domain: "NSOSStatusErrorDomain" - code: 18446744073709517598

The change from

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>keychain-access-groups</key>
	<array>
		<string>$(AppIdentifierPrefix)TEST</string>
		<string>$(AppIdentifierPrefix)com.microsoft.msalcache</string>
	</array>
</dict>
</plist>
```

to 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>keychain-access-groups</key>
	<array>
		<string>$(AppIdentifierPrefix)TEST</string>
		<string>$(AppIdentifierPrefix)com.microsoft.adalcache</string>
	</array>
</dict>
</plist>
```

Why has the cache name gone back to `adalcache` when this is the MSAL library?

I would suggest maybe that you provide the steps of the things that have changed between these versions so that people trying to keep up can follow on.

**Comment by danieldobalian** [comment]
@jthake-msft thanks for the report + feedback. Going forward, you can expect there to be guidance for incoming API changes as well as explanations on what we changed and why. 

On your question for `adalcache`.  This name is the default; however, it can always be overridden.  The crux of why it's now defaulted to `adalcache` is for token sharing between apps.  Because there are ADAL apps already built that you may want to share tokens with (and it may be challenging to update) we decided to make keep the default as `adalcache`. This prevents apps from having to add 2 separate entries for their token cache into the keychain. 

More info here: https://github.com/AzureAD/microsoft-authentication-library-for-objc/wiki/Keychain-on-iOS.

When we do the next round of improvements on this sample the points you highlighted will be more explicit and documented. Thanks again for all the recommendations. In the meantime, leaving this issue open.
