### ISSUE TITLE
Library working in XCode environment but produces error code 34018 in production

### ISSUE THREAD

**Issue by menasheu** [Azure-Samples/ms-identity-mobile-apple-swift-objc#79]
Hi,
We use the MSAL library 1.1.25 (but the problem occurred also with 1.1.24) and everything works fine when in the application is loaded from XCode. However when we produce an ipa file and either export it or upload to the store the user gets the following error:

**_Couldn't query current account with error: Error Domain=NSOSStatusErrorDomain Code=-34018 "(null)" UserInfo={MSALErrorDescriptionKey=Failed to get items from keychain.}_**

com.microsoft.adalcache is correctly defined in the Keychain Sharing. Same for the entitlements.

**Comment by mipetriu** [comment]
@menasheu Since the application is working correctly when you're running it in XCode, there could be an issue with the device you're using to test the ipa? Or maybe with the code signing between development and distribution versions? There is an [in-depth troubleshooting guide](https://developer.apple.com/forums/thread/114456) in Apple forums that has been compiled to help find the root cause of errors with this code.

**Comment by menasheu** [comment]
Thanks a lot.
It was indeed a stupid issue as expected. The Keychain Sharing was missing the com.microsoft.adalcache in Release mode (it was only in the Debug...)
Thanks a lot. The library is working perfectly.

**Comment by mipetriu** [comment]
@menasheu Great, I'm glad to hear you were able to find it!
